# Generated by Django 3.0.5 on 2020-05-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Slug', models.SlugField(unique=True)),
                ('Brief', models.TextField(max_length=100)),
                ('MainText', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='p', max_length=20)),
                ('PostTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Author')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
