# Generated by Django 3.1.3 on 2020-12-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Images_Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Slug', models.SlugField(blank=True, unique=True)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Slug', models.SlugField(unique=True)),
                ('Brief', models.TextField(max_length=100)),
                ('MainText', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(null=True, upload_to='app/static/img/post')),
                ('Status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='p', max_length=20)),
                ('PostTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Slug', models.SlugField(unique=True)),
                ('Brief', models.TextField(max_length=100)),
                ('MainText', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='app/static/img/post/default_news.jpg', null=True, upload_to='app/static/img/post')),
                ('Status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='p', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='app/static/img/meet')),
                ('image_rel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.images_desc')),
            ],
        ),
    ]
