# Generated by Django 3.0.5 on 2020-05-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Slug',
            field=models.SlugField(unique=True),
        ),
    ]
