# Generated by Django 3.1.3 on 2020-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_desc',
            name='image',
            field=models.FileField(blank=True, upload_to='app/static/img/meet'),
        ),
    ]
