# Generated by Django 3.1.3 on 2020-12-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201201_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images_Desc',
            new_name='Images_Info',
        ),
    ]
