# Generated by Django 3.0.5 on 2020-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200528_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='app/static/img/post', verbose_name='raouf'),
        ),
    ]
