# Generated by Django 3.1.3 on 2020-12-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201202_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='images_url',
        ),
    ]
