# Generated by Django 3.0.5 on 2020-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200528_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='raouf',
            field=models.ImageField(null=True, upload_to='app/static/img/post'),
        ),
    ]
