# Generated by Django 3.1.3 on 2020-12-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Slug', models.SlugField(unique=True)),
                ('Brief', models.TextField(max_length=100)),
                ('MainText', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='app/static/img/events/default_news.jpg', null=True, upload_to='app/static/img/events')),
                ('Status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='p', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
